[package]
name = "axcut_macros"

# Inherited from workspace Cargo.toml
version.workspace = true
edition.workspace = true

[lib]
proc-macro=true

[dependencies]
axcut = { path="../../axcut"}
quote = "1.0"
proc-macro2 = "1.0"
syn = { version= "2.0", features =["full"] }
