[package]
name = "core2axcut"

version.workspace = true
edition.workspace = true

[dependencies]
# Workspace members
axcut     = { workspace = true }
core_lang = { workspace = true }
printer   = { workspace = true }
