[package]
name = "eval_scc"

# Inherited from workspace Cargo.toml
version.workspace = true
edition.workspace = true

[[bin]]
name = "eval_scc"
path = "src/main.rs"

[dependencies]
basic-toml = { version = "0.1.9" }
serde = { version = "1.0.217",features=["derive"] }
