[package]
name = "axcut2aarch64"

version.workspace = true
edition.workspace = true

[dependencies]
# Workspace members
axcut         = { workspace = true }
axcut2backend = { workspace = true }
printer       = { workspace = true }

[dev-dependencies]
goldenfile = { workspace = true }
